version: "3.5"

services:
  mysql:
    container_name: "mars-mysql"
    image: "mysql:8.0.19"
    platform: linux/x86_64
    security_opt:
      - seccomp:unconfined
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: mars123456
      MYSQL_DATABASE: mars
      MYSQL_USER: mars
      MYSQL_PASSWORD: 123456
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d/
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/logs
    command:
      --lower-case-table-names=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    networks:
      network:
        ipv4_address: 10.66.66.4
    restart: always
networks:
  network:
    name: "idc-network"
    ipam:
      config:
        - subnet: 10.66.66.0/24
          gateway: 10.66.66.1
